apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
  labels:
    app: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
       app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
        - name: ldap
          image: osixia/openldap:1.1.11
          volumeMounts:
            - name: ldap-data
              mountPath: /var/lib/ldap
            - name: ldap-config
              mountPath: /etc/ldap/slapd.d
            - name: ldap-certs
              mountPath: /container/service/slapd/assets/certs
          ports:
            - containerPort: 389
              name: openldap
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
          env:
            - name: LDAP_ORGANISATION
              value: "IBM"
            - name: LDAP_DOMAIN
              value: "cloudpak.ibm"
            - name: LDAP_ADMIN_PASSWORD
              value: "cloudPakPassw0rd!"
            - name: LDAP_CONFIG_PASSWORD
              value: "cloudPakPassw0rd!"
            - name: loglevel
              value: "debug"
      volumes:
        - name: ldap-data
          persistentVolumeClaim:
            claimName: ldap-data
        - name: ldap-config
          persistentVolumeClaim:
            claimName: ldap-config
        - name: ldap-certs
          persistentVolumeClaim:
            claimName: ldap-certs
      serviceAccount: robo
      serviceAccountName: robo
